### ISSUE TITLE
Multiple PHP-FPM instances running w/ php71u-fpm-7.1.10-1.ius.centos6.x86_64

### ISSUE THREAD

**Issue by ghost** [iuscommunity-pkg/php71u#11]
Hi,

I installed php71u-fpm-7.1.10-1.ius.centos6.x86_64 on an Amazon Linux (AMI release 2017.09) instance and restarting the service gives the following error:

```
[root@ip-172-31-1-30 log]# service php-fpm restart
Stopping php-fpm:                                          [FAILED]
Starting php-fpm: 
[17-Oct-2017 15:30:11] ERROR: An another FPM instance seems to already listen on /run/php-fpm/www.sock
[17-Oct-2017 15:30:11] ERROR: FPM initialization failed
                                                           [FAILED]
```

There's are custom settings in `/etc/php-fpm.d/www.conf` but the problem persists when it's replaced by the packaged version.

It appears that the problem was introduced here:
https://github.com/iuscommunity-pkg/php71u/commit/f7f5d837c3a28c889f467d15d517e4ad49fb6fda#diff-3c25e7164d6790dc4d45c3ec547d0cdfR20

Uncommenting the pid file path fixes the problem.

-P

**Comment by b-harper** [comment]
Hey @p-pawlak,

Thanks for taking the time to submit this issue.  First, I have to point out that IUS does not support Amazon Linux.  That being said, I am seeing similar behavior on CentOS 6.  I am able to start php-fpm, but I am unable to stop it cleanly.  I had to `killall php-fpm` to stop it.  Once there are no php-fpm processes and the pid file path is uncommented, I am able to start/stop/restart cleanly.  

I will work on getting updated packages built ASAP.

**Comment by b-harper** [comment]
Hey @p-pawlak,

Thanks for taking the time to submit this issue.  First, I have to point out that IUS does not support Amazon Linux.  That being said, I am seeing similar behavior on CentOS 6.  I am able to start php-fpm, but I am unable to stop it cleanly.  I had to `killall php-fpm` to stop it.  Once there are no php-fpm processes and the pid file path is uncommented, I am able to start/stop/restart cleanly.  

I will work on getting updated packages built ASAP.

**Comment by b-harper** [comment]
Updated packages have been built and will get pushed into the stable repositories during tonight's automation run.  Typically, we would not release packages directly to the stable repositories.  Given the nature of issue, and how easy it is to verify correct functionality, we will make an exception.
