### ISSUE TITLE
Cannot install mod_php71u + httpd24u on CentOS 6

### ISSUE THREAD

**Issue by draxxris** [iuscommunity-pkg/php71u#14]
mod_php71u wants httpd-mmn = 20051115 which is of course not present in httpd24u, its only present in the vanilla CentOS httpd (2.2) packages.

I think it will probably require a "httpd24u-mod_php71u" package.

**Comment by carlwgeorge** [comment]
Same answer as https://ius.io/FAQs/#why-cant-i-install-php56u-with-httpd24u.
