### ISSUE TITLE
7.1.29

### ISSUE THREAD

**Issue by bgibson710** [iuscommunity-pkg/php71u#17]
I see 7.2.18 is in pre-release but I don't see anything for 7.1.29.  Is that already in the pipeline?  If not can we get it in there soon?

**Comment by carlwgeorge** [comment]
Whoops, thanks for the heads up!  I saw 7.3.5 and 7.2.18 get released on Thursday 2019-05-02, but then missed 7.1.29 getting released the next day.  Then I was out of the office the whole next week.  I'm working on this now.

**Comment by carlwgeorge** [comment]
[Done](https://github.com/iusrepo/php71u/commit/c94e3d7c61f518bcefea10c0898f9efea2e5de48). To test the packages, you'll need to switch to the new [IUS CDN](https://github.com/iusrepo/infrastructure/issues/14#issuecomment-488866147) and install them from the ius-testing repo.

**Comment by carlwgeorge** [comment]
This has been published to the stable repo.
