### ISSUE TITLE
7.1.30

### ISSUE THREAD

**Issue by BjornTwachtmann** [iuscommunity-pkg/php71u#19]
PHP 7.1.30 has been out for a while and contains some fairly important security fixes: https://www.php.net/ChangeLog-7.php#PHP_7_1 . Any chance of getting that in the repo?

**Comment by carlwgeorge** [comment]
Sorry for the confusion.  We are in the middle of a [switch from the mirror network to a CDN](https://github.com/iusrepo/infrastructure/issues/14).  The [php71u-7.1.30-1](https://github.com/iusrepo/php71u/releases/tag/7.1.30-1) release was published on the CDN shortly after it's upstream release.  I hadn't released it on the mirror network yet, until your reminder (thanks).

To avoid any future delays please go ahead and update your ius-release package from the testing repository to switch to the CDN.  In the next few weeks I plan to push that new ius-release package to the stable repo.

```
yum --enablerepo ius-testing update ius-release
yum --enablerepo ius-testing clean all
```
