### ISSUE TITLE
Zend OPcache

### ISSUE THREAD

**Issue by agarzon** [iuscommunity-pkg/php71u#3]
Hi.

I was unable to find Zend OPcache in IUS repo for PHP 7.1

Same for INTL extension

**Comment by b-harper** [comment]
Hey @agarzon,

Thanks for taking the time to contact us.  Both of those modules are available in the stable repositories.

```
$ rpm -qa |grep -i php
php71u-common-7.1.0-3.ius.centos7.x86_64
php71u-fpm-7.1.0-3.ius.centos7.x86_64
php71u-opcache-7.1.0-3.ius.centos7.x86_64
php71u-cli-7.1.0-3.ius.centos7.x86_64
php71u-intl-7.1.0-3.ius.centos7.x86_64
```

If you are having issues downloading those packages, please provide information about your yum configuration and any errors.

**Comment by agarzon** [comment]
Thank you, for some reason is not listed here: 

https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/repoview/development.languages.group.html

**Comment by b-harper** [comment]
The php71u-opcache package is clearly listed:

```
$ curl -s https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/repoview/development.languages.group.html |grep php71u-opcache
            <a href="php71u-opcache.html" class="inpage">php71u-opcache</a> -
```

The php71u-intl package is listed under [system environment/libraries][0]:

```
$ curl -s https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/repoview/system_environment.libraries.group.html |grep php71u-intl
            <a href="php71u-intl.html" class="inpage">php71u-intl</a> - 
```
[0]: https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/repoview/system_environment.libraries.group.html
