### ISSUE TITLE
Disable pcre JIT compilation by default

### ISSUE THREAD

**Issue by carlwgeorge** [iuscommunity-pkg/php71u#7]
See https://github.com/iuscommunity/infrastructure/issues/5.

**Comment by carlwgeorge** [comment]
I can see that this has already been applied to [Fedora's php 7.1](https://src.fedoraproject.org/cgit/rpms/php.git/commit/?id=f5482baa0c1ae8a3063bbaf342ea7634f759d4de).  We'll implement the same fix.

**Comment by b-harper** [comment]
[pcre.jit=0][0] is already set in php71u.


[0]: https://github.com/iuscommunity-pkg/php71u/blob/master/SOURCES/php.ini#L966
