### ISSUE TITLE
PHP error on restart for EL6

### ISSUE THREAD

**Issue by Xon** [iuscommunity-pkg/php71u#8]
On a CentOS6 VM I haven't had a chance to upgrade to CentOS7/EL7, the recent php 7.1.8 update causes this error on install or restart;
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/sqlite3.so' - /usr/lib64/php/modules/sqlite3.so: undefined symbol: sqlite3_errstr in Unknown on line 0
```

yum whatprovides /usr/lib64/php/modules/sqlite3.so
```
php71u-pdo-7.1.8-1.ius.centos6.x86_64 : A database access abstraction module for PHP applications
Repo        : installed
Matched from:
Other       : Provides-match: /usr/lib64/php/modules/sqlite3.so
```

This isn't a critical blocker for me, but it looks like a breaking change slipped in to the php 7.1.8 sqlite update for EL6, but not EL7

**Comment by b-harper** [comment]
Hey @Xon,

Thanks for taking the time to submit this issue.  I am able to create this issue.

```
$ cat /etc/redhat-release 
CentOS release 6.9 (Final)

$ rpm -qa |grep php
php71u-pdo-7.1.8-1.ius.centos6.x86_64
php71u-cli-7.1.8-1.ius.centos6.x86_64
php71u-common-7.1.8-1.ius.centos6.x86_64

$ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/sqlite3.so' - /usr/lib64/php/modules/sqlite3.so: undefined symbol: sqlite3_errstr in Unknown on line 0
PHP 7.1.8 (cli) (built: Aug  3 2017 14:01:26) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

I'll investigate this issue.

**Comment by b-harper** [comment]
Updated packages have been built and are available in the testing repositories.  Let us know if these are working for you.

**Comment by Xon** [comment]
Cheers, that appears to have fixed it.

**Comment by b-harper** [comment]
The updated package will be hitting the stable repositories after tonight's automation.
